Hw1
Rustam-Khamidullin/Java_Bot pull request #1
Opened 2024-02-17 11:07 UTC by Rustam-Khamidullin

2024-02-18 12:06 UTC, lwbeamer reviewed
Бонусное задание ожидать или не будет?)

2024-02-18 12:06 UTC, lwbeamer commented on .github/workflows/scrapper.yml
> +name: Bot Build
В `scrapper.yml` точно должен быть `Bot Build`?)

2024-02-18 12:06 UTC, lwbeamer commented on .github/workflows/scrapper.yml
> +        run: mvn -pl bot -am package
Аналогично, кажется ты случайно превратил (тут и в других местах файла) scrapper.yml в bot.yml. У тебя scrapper на этом этапе пустой и менять в его workflow ничего не нужно, он итак должен без проблем собираться)

2024-02-18 12:06 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/Botik.java
> +                SendMessage sendMessage = process(update);
В дальнейшем тут и в других проектах когда код будет расти, перестанет быть понятно, что это за метод такой и что он импортнулся из другого класса. Поэтому лучше явно указать класс, откуда вызывается статический метод - `UserMessageProcessor.process(udate)`.

Исключения есть, но как правило статически импортят в тех случаях, когда однозначно понятно что за метод, как правило из общеизвестных классов типа `java.lang.Math` или `org.junit.jupiter.api.Assertions`.

2024-02-18 12:06 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/UserMessageProcessor.java
> +        for (Command cmd : availableCommands()) {
Аналогично, понятней будет `Command.availableCommands()`

2024-02-18 12:06 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/UserMessageProcessor.java
> +        String text = update.message().text();
если `message()` вернет null все упадет с NPE. Нужно это учесть

2024-02-18 12:06 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/UserMessageProcessor.java
> +        long chatId = update.message().chat().id();
Здесь тоже потенциальный NPE (Null Pointer Exception)

2024-02-18 12:06 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/UserMessageProcessor.java
> +        Command command = NAME_TO_CMD.getOrDefault(cmdName, null);
Кажется сюда можно сразу передавать текст сообщения и нужда в регулярке и в Matcher'е отпадет вообще. Соотвественно метод parseCommandName() можно превратить в просто извлечение текста из сообщения. Сократится код и будет работать быстрее, без процессинга регулярок

2024-02-18 12:06 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/command/Command.java
> +    }
Так как команды не являются бинами (так тоже ок, ведь спринг вы только начинаете изучать), то часть логики по внедрению зависимостей нужно брать на себя, что ты и делаешь. Но здесь выходит так, что каждый вызов `availableCommands()` вернет новый список команд, что не есть хорошо ибо зачем нам плодить в памяти листы с объектами, если достаточно создать его один раз. Поэтому нужно реализовать singleton лист с командами, чтобы он создался один раз, а в последующие вызовы переиспользовался

2024-02-18 12:06 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/command/Help.java
> +    private static String generateAnswer() {
`static`?

2024-02-18 12:06 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/Botik.java
> +
здесь специально package-private модификатор доступа? Чаще если не предусмотрено иного везде делают private, чтобы повысить инкапсуляцию - если это специально сделано, то расскажи почему)

2024-02-18 12:06 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/command/Track.java
> +    }
`/track ` подразумевает что ты передашь ссылку каким-то образом - следующим сообщением, в ответе или сразу вместе с командой (тут уже на твое усмотрение). Надо продумать как ты будешь обрабатывать этот случай, то есть понимать какую ссылку тебе передали при команде `/track`. Можешь исправить в рамках следующей дз, тут зачту итак, но без этого дальше никак не обойтись. Для `/untrack` аналогично

2024-02-18 12:37 UTC, Rustam-Khamidullin commented
Нашел в гугле что меню можно добавить через BotFather.  Я так понимаю можно и в коде это сделать) Попробую еще api поизучать тогда))

2024-02-23 16:53 UTC, lwbeamer requested changes

2024-02-23 16:53 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/UserMessageProcessor.java
> +        }
Лучше перенести эту проверку на уровень выше, в метод `setUpdatesListener` и выкидывать NPE руками не нужно - просто можно проигнорировать update, который равен null

2024-02-23 16:53 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/UserMessageProcessor.java
>          long chatId = update.message().chat().id();
у update всегда есть (не равен null) message?

2024-02-23 16:53 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/UserMessageProcessor.java
> +    }
Это чтобы процессить команды типа /track *ссылка*? Если да, то:
1) Проверять message на null лучше на уровне выше, передавать null в качестве аргумента не очень хорошая практика, лучше отсекать их как можно раньше
2) Можешь добавить в имя команды "/" в начало и не надо будет тут это проверять вообще. К тому же смысла сейчас в этом немного, ибо я могу написать /`goisjdfo oibjdo`, проверку пройдет, хотя команды такой нет
3) У тебя в parts[0] по факту уже будет имя команды. Вот его и передай в 
`Command command = NAME_TO_CMD.getOrDefault(cmdName, null);`
Для этого можешь сделать чтобы этот метод возращал пару значений - можешь сделать класс Pair внутренний или возвращать массив строк, а потом в нем брать по индексам команду и аргумент

2024-02-23 16:53 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/UserMessageProcessor.java
> +    }
Если по предыдущему комменту сделаешь по пункту 3, то 
весь этот метод вообще можно будет убрать

2024-02-23 16:58 UTC, lwbeamer commented
> Нашел в гугле что меню можно добавить через BotFather. Я так понимаю можно и в коде это сделать) Попробую еще api поизучать тогда))

А там оно обновляется автоматически если ты добавишь новые команды или поменяешь у них имя/описание? Не проверял, но мне кажется что нет. Сейчас у тебя в коде динамически берется их классов команд, и если что-то поменяешь, при перезапуске приложения в боте меню тоже изменится

2024-02-25 10:08 UTC, merged

2024-03-02 13:56 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/Botik.java
> +                }
Замени это на 

```
if (update == null || update.message == null || update.message.text == null) {
    continue;
}
```

2024-03-02 13:56 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/Botik.java
> +                }
Тогда вот это уйдет (вместе с try)

Потому что сейчас ты игноришь любой TelegramException, а вдруг в будущем будешь его кидать еще по какому-то поводу, и уже потребуется обработка? Все сломается ибо не будет обработки. Но сейчас у тебя выброс исключения никакой функции не несет кроме проверки полей на null, которую ты частично делаешь выше. Чтобы делать ее не частично, а полностью - учти коммент выше и try-catch отсюда уйдет)

2024-03-02 13:56 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/UserMessageProcessor.java
> +            NAME_TO_CMD.put("/" + cmd.command(), cmd);
Я имел в виду в возвращаемую методом cmd.command() строку добавить слеш и не придется писать такие конструкции

2024-03-02 13:56 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/command/Help.java
> +        return "help";
Сюда -->` return "/help";`
и в других командах аналогично

2024-03-02 13:56 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/service/UserMessageProcessor.java
> +        String cmdName = parseTelegramCommandArgument(text).command;
У тебя метод справа возвращает пару команда-аргумент; Подход мне нравится, но аргумент ты тут проигнорировал из возвращаемого рекорда)
 Как он до команд /track /untack доходит в итоге? Нужно докрутить