ready for PR
Rustam-Khamidullin/Java_Bot pull request #3
Opened 2024-03-03 17:56 UTC by Rustam-Khamidullin

2024-03-08 17:15 UTC, lwbeamer requested changes

2024-03-08 17:15 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/client/ScrapperClient.java
> +@SuppressWarnings("MultipleStringLiterals")
Это неспроста, го вынесем повторяющие литералы типа "/tg-chat/", "Tg-Chat-Id" и т.д. в константы чтоб ворнинг ушел сам собой

2024-03-08 17:15 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/client/ScrapperClient.java
> +    public ResponseEntity<ListLinksResponse> getAllLinks(long tgChatId) {
C какой целью возвращаешь здесь и в других методах ResponseEntity, а не сразу dto?

2024-03-08 17:15 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/controller/Api.java
> +        }
Это как я понимаю заглушка? А в каких реальных случаях он может быть некорректным? Кажется это лишнее ибо если придет некорректное тело запроса, то спринг сам выкинет исключение, потому что весит `@Valid` и аннотации `@NotNull`,`@NotBlank` в dto

2024-03-08 17:15 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/controller/Api.java
> +        return ResponseEntity.ok("Обновление обработано");
По спецификации тело в этом запросе не возвращается тело, го уберем

2024-03-08 17:15 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/controller/ApiExceptionHandler.java
> +            getStackTaraceList(e)
Не критично, но Java позволяет сократить этот метод до одной строки с помощью Stream API)

2024-03-08 17:15 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/dto/scrapper/request/AddLinkRequest.java
> +public record AddLinkRequest(@JsonProperty("link") String link) {
Без `@JsonProperty` точно не работает? Кажется тут и в других рекордах можно обойтись без неё. Имена полей совпадают с таковыми в JSON

2024-03-08 17:15 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/client/ScrapperClient.java
> +    public ScrapperClient(String baseUrl) {
А baseUrl добавил в проперти? В скраппере вижу, а тут не нашел

2024-03-08 17:15 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/controller/Api.java
> +        return ResponseEntity.ok().body("Чат зарегистрирован");
Без тела по API

2024-03-08 17:15 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/controller/Api.java
> +        return ResponseEntity.ok().body("Чат успешно удалён");
Тут тоже

2024-03-08 17:15 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/exception/api/BadRequestException.java
> +    private final String description;
Для того что ты сейчас пишешь в это поле, как раз и существует уже встроенное поле message, а это можно убрать)

2024-03-08 17:15 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/exception/api/NotFoundException.java
> +    private final String description;
Аналогично

2024-03-10 12:06 UTC, Rustam-Khamidullin commented on bot/src/main/java/edu/java/bot/client/ScrapperClient.java
> +    public ResponseEntity<ListLinksResponse> getAllLinks(long tgChatId) {
Я думал так возвращать код ответа

2024-03-10 12:36 UTC, Rustam-Khamidullin commented on bot/src/main/java/edu/java/bot/dto/scrapper/request/AddLinkRequest.java
> +public record AddLinkRequest(@JsonProperty("link") String link) {
В  AddLinkRequest убрал, все хорошо. Ели убираю в LinkResponse или ListLinksResponse тесты падают.

2024-03-16 10:46 UTC, merged