Hw7
Rustam-Khamidullin/Java_Bot pull request #9
Opened 2024-03-31 19:20 UTC by Rustam-Khamidullin

2024-03-31 19:26 UTC, Rustam-Khamidullin commented
С bucket4j возникли проблемы. Я очень хотел настроить его полностью через конфигурационный файл, как здесь https://www.baeldung.com/spring-bucket4j и здесь https://github.com/MarcGiffing/bucket4j-spring-boot-starter?tab=readme-ov-file#introduction_filter, но у меня почему то не работает. Можете подсказать в чем может быть проблема.

2024-04-07 16:49 UTC, lwbeamer requested changes
По ретраям ОК. А что именно с rate limit не работает? Насчет фильтов - ты можешь тот же фильтр что ты скинул сделать в виде кода. Нужно будет унаследовать интерфейс jakarta.servlet.Filter и переопределить doFilter() в котором брать бакет по айпи и проверять лимит, если превышен - отфильтровывать запрос с 429 кодом

2024-04-13 09:17 UTC, Rustam-Khamidullin commented
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. У меня по этой причине стали падать тесты. Я так понимаю, что при старте тестов запускается приложение и не может подключиться к постгресу. Локально все работает. Как можно исправить?

2024-04-13 12:19 UTC, lwbeamer commented
> org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. У меня по этой причине стали падать тесты. Я так понимаю, что при старте тестов запускается приложение и не может подключиться к постгресу. Локально все работает. Как можно исправить?

Локально у тебя запущен контейнер с БД, который ты прописал в компоузе, поэтому все ок. В пайплайне как я понимаю БД не поднимается, поэтому и подключаться не к чему. Но пока не особо понимаю почему оно раньше билдилось, поузнаю у коллег, пока не обращаю на это внимание при проверке)

2024-04-13 12:26 UTC, lwbeamer commented on scrapper/src/test/java/edu/java/scrapper/client/BotClientTest.java
> +        Assertions.assertThrows(HttpClientErrorException.class, () -> botClient.sendUpdate(request));
А как в этой строчке проверяется, что исключение кинуто именно 4 раза? Он же ничем не отличается от того, что в тесте ниже

2024-04-28 04:04 UTC, merged